services:
  - type: web
    name: nutri-nube-app
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: flask run --host=0.0.0.0
    ports:
      - 5000
    envVars:
      - key: DATABASE_URL
        value: postgresql://pfeiferj:NutriNube@db:5432/flaskdb
    healthCheck:
      path: /
      protocol: http
      port: 5000
    docker:
      image: ghcr.io/pfeifer-j/nutrinube:2.0.0
      volumes:
        - ./src/app:/app

  - type: database
    name: nutri-nube-db
    env: postgres
    version: "13"
    envVars:
      - key: POSTGRES_USER
        value: pfeiferj
      - key: POSTGRES_PASSWORD
        value: NutriNube
      - key: POSTGRES_DB
        value: flaskdb

  - type: worker
    name: fluentd-logger
    env: docker
    dockerfilePath: ./fluentd/Dockerfile
    buildCommand: ""
    startCommand: fluentd -c /fluentd/etc/fluent.conf
    ports:
      - 24224
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - nutri_nube_logs:/fluentd/log

  - type: worker
    name: fluentd
    env: docker
    dockerfilePath: ./fluentd/Dockerfile
    buildCommand: ""
    startCommand: fluentd -c /fluentd/etc/fluent.conf
    ports:
      - 24224

volumes:
  nutri_nube_db:
  nutri_nube_logs:
